Arrays

In [1]:
import numpy

def arrays(arr):
    rev=arr[::-1]
    return numpy.array(rev,float)

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 5 6
[6. 5. 4. 3. 2. 1.]


In [2]:
import numpy as np


Shape and Reshape

In [8]:
lis=[]
for i in range(0,9):
   lis.append(input("enter elements of list"))
my=np.array(lis)
np.reshape(my,(3,3))

enter elements of list1
enter elements of list2
enter elements of list3
enter elements of list4
enter elements of list5
enter elements of list6
enter elements of list7
enter elements of list8
enter elements of list9


array([['1', '2', '3'],
       ['4', '5', '6'],
       ['7', '8', '9']], dtype='<U1')

Transpose

In [10]:
n=int(input("enter number of rows"))
m=int(input("enter number of columns"))
li=[]
for i in range(0,n*m):
    li.append(int(input("enter a value:")))
arr=np.array(li)
arr2=arr.reshape(n,m)
print(np.transpose(arr2))
print(arr.flatten())

enter number of rows5
enter number of columns4
enter a value:1
enter a value:2
enter a value:3
enter a value:4
enter a value:5
enter a value:6
enter a value:7
enter a value:8
enter a value:9
enter a value:10
enter a value:11
enter a value:12
enter a value:13
enter a value:14
enter a value:15
enter a value:16
enter a value:17
enter a value:18
enter a value:19
enter a value:20
[[ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]
 [ 4  8 12 16 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


concat

In [14]:
a, b, c = map(int,input().split())
arrA = np.array([input().split() for _ in range(a)],int)
arrB = np.array([input().split() for _ in range(b)],int)
print(np.concatenate((arrA, arrB), axis = 0))
    

3 4 2
1 2
1 4
1 3
1 5
1 6
1 7
1 8
[[1 2]
 [1 4]
 [1 3]
 [1 5]
 [1 6]
 [1 7]
 [1 8]]


zeros and ones

In [20]:
nums = tuple(map(int, input().split()))
print (numpy.zeros(nums, dtype = numpy.int))
print (numpy.ones(nums, dtype = numpy.int))


3 3 3 
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


<ipython-input-20-f0b9a68b43d0>:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print (numpy.zeros(nums, dtype = numpy.int))
<ipython-input-20-f0b9a68b43d0>:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1

eye and identity

In [22]:
numpy.set_printoptions(sign=' ')
print(numpy.eye(*map(int, input().split())))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


array mathematics

In [23]:
n, m = map(int, input().split())
a, b = (np.array([input().split() for _ in range(n)], dtype=int) for _ in range(2))
print(a+b, a-b, a*b, a//b, a%b, a**b, sep='\n')

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


floor and ceil

In [24]:
numpy.set_printoptions(sign=' ')

a = numpy.array(input().split(),float)

print(numpy.floor(a))
print(numpy.ceil(a))
print(numpy.rint(a))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


sum and prod

In [26]:
print(np.prod(np.sum(np.array([input().split() for _ in range(int(input().split()[0])) ],int),axis=0)))

2 2 
1 2
3 4
24


min and max

In [28]:
arr=[]
n,m=map(int,input().split())
for row in range(n):
    my_arr=list(map(int,input().split()))
    arr.append(my_arr)
my_array=numpy.array(arr)
result=numpy.min(my_array, axis = 1)
print(max(result))

2 2
1 3
4 5
4


mean,var and std

In [29]:
array = []
n, m = map(int, input().split())
for _ in range(n): array.append(list(map(int, input().split())))
array = numpy.array(array)
print(numpy.mean(array, axis=1))
print(numpy.var(array, axis=0))
print(round(numpy.std(array), 11))

4 3
1 2 3
3 2 1
4 5 6
1 4 6
[ 2.          2.          5.          3.66666667]
[ 1.6875  1.6875  4.5   ]
1.77169096879


dot and cross

In [34]:
a=int(input())

arr1=numpy.array([list(map(int,input().split())) for _ in range(a)])

arr2=numpy.array([list(map(int,input().split())) for _ in range(a)])

print(numpy.dot(arr1,arr2))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [ ]:
polynomials

In [35]:
n = list(map(float,input().split()));
m = input();
print(numpy.polyval(n,int(m)));

1.1 2 3
0
3.0
